# .github/workflows/main.yml
name: Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests gnupg python-git

    - name: Run Python script
      env:
        INPUT_GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
      run: python main.py

    - name: Upload GPG key to GitHub
      env:
        INPUT_GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
      run: |
        gpg --export-secret-keys --armor minhquan68 | curl -X POST -H "Authorization: token $INPUT_GITHUB_TOKEN" -H "Content-Type: application/json" -d @- https://api.github.com/user/gpg_keys

    - name: Import GPG key from GitHub
      env:
        INPUT_GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
      run: |
        gpg --import <(curl -H "Authorization: token $INPUT_GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/gpg_keys | jq -r .armored_public_key)

    - name: Verify imported GPG keys
      run: gpg --list-secret-keys

    - name: Configure Git to use GPG key
      run: |
        git config --global user.signingkey minhquan68
        git config --global commit.gpgsign true

    - name: Run Python script with signed commits
      env:
        INPUT_GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
      run: python main.py
