name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      GITHUB_TOKEN:
        description: 'GitHub Token'
        required: true

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests python-gnupg

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ github.event.inputs.GITHUB_TOKEN }}
      run: |
        python script.py
